### PR TITLE
ANTLR4 upgrade to 4.10.1

### PR DESCRIPTION
**Pull request by maxirmx**
Hello
It is @maxirmx  again )     
I drafted a version that can be configured for antlr 4.8.x - 4.10.x 
Your feedback is much appreciated
Thank you 

cc: @ronaldtse

This is a contribution from [Metanorma](https://www.metanorma.org/) ([GitHub](https://github.com/metanorma)), a product of [Ribose](https://www.ribose.com/) ([GitHub](https://github.com/riboseinc)).

### CODE REVIEW

**Comment by camertron** [comment]
Hey @maxirmx, thanks for this :) What would you think about simply updating the version of ANTLR that's distributed with the gem? I'm not really interested in supporting multiple versions, so let's just go with the most recent ANTLR release.

**Comment by maxirmx** [comment]
Sure. I am interested in the latest ANTLR version only
Just did my best to offer various options

**Review by camertron — APPROVED** [review]
Looks good 🚀

**Comment by camertron** [comment]
Published in v2.1.0.

**Comment by maxirmx** [comment]
Thank you, @camertron

**Pull request merged**
