### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by zakjan**
Although Rice oficially doesn't support Windows, it works with the following changes.

https://jasonroelofs.com/rice/

### CODE REVIEW

**Comment by camertron** [comment]
@zakjan huh interesting. I'm not much of a C++ guy - I assume `#include <iostream>` will still work with *nix compilers?

**Comment by zakjan** [comment]
Yes, compiles on Linux, Mac, Windows

**Comment by zakjan** [comment]
You can check the compiler input in Github Actions output at https://github.com/lutaml/expressir/pull/33

**Comment by camertron** [comment]
Good enough for me :)

**Comment by camertron** [comment]
@zakjan is this a good time to release a new version of the gem?

**Comment by zakjan** [comment]
Yes, I'm done, thanks :)

**Comment by camertron** [comment]
Published along with #3, #4, and #5 as v1.1.0.

**Pull request merged**
