### PR TITLE
Add context and token methods to allow accessing tokens on user-defined channels

### PR DESCRIPTION
**Pull request by zakjan**
Add context and token methods:

Context
- start
- stop

Token
- channel
- token_index

Also it needs to_ruby<Token*> to be moved before ContextProxy.

This is the first step to allow accessing tokens on user-defined channels.

---

For now, I access all tokens with a simple ParserProxy method returning an array of all tokens.

```
Array getTokens() {
  Array a;

  std::vector<Token*> tokens = this -> tokens -> getTokens();

  for (auto &token : tokens) {
    a.push(token);
  }

  return a;
}
```

I'm leaving it here for reference only, no PR, because proper implementation should expose TokenStream proxy and methods instead.

### CODE REVIEW

**Comment by camertron** [comment]
I'm ok with this change, but I don't really understand what your goal is. Why do you need access to all the tokens?

**Comment by zakjan** [comment]
To be able to read tokens from custom channels. Usually this is done with BufferedTokenStream methods such as getHiddenTokensToRight, which takes channel id as the second argument.

**Comment by camertron** [comment]
@zakjan ok interesting. What do custom channels do? I've never used them before.

**Comment by zakjan** [comment]
It's for secondary tokens, which can be processed separately from the main grammar. This SO question roughly illustrates my use case - processing doc comments which can appear anywhere in the input. https://stackoverflow.com/questions/12485132/catching-and-keeping-all-comments-with-antlr The first accepted answer is not a good solution, see others.

The Definitive ANTLR 4 Reference, section 12.1 Broadcasting Tokens on Different Channels contains intro to the topic.

**Comment by camertron** [comment]
Super interesting, thanks!

**Pull request merged**
